---
abstract: 'Properties file parser for Maketext'
author:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  Test::More: 0.98
  parent: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Locale-Maketext-Lexicon-Properties
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Locale::Maketext::Lexicon::Properties:
    file: lib/Locale/Maketext/Lexicon/Properties.pm
    version: 0.01
requires:
  Encode: 0
  Locale::Maketext::Lexicon: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/moznion/Locale-Maketext-Lexicon-Properties/issues
  homepage: https://github.com/moznion/Locale-Maketext-Lexicon-Properties
  repository: git://github.com/moznion/Locale-Maketext-Lexicon-Properties.git
version: 0.01
x_contributors:
  - 'moznion <moznion@gmail.com>'
